### ISSUE TITLE
org.red5.net.websocket.WebSocketPlugin cannot be cast

### ISSUE THREAD

**Issue by mikechy2005** [Red5/red5-websocket#4]
Hello, I followed the example code and build the project
but i cant startup my application

java.lang.ClassCastException: org.red5.net.websocket.WebSocketPlugin cannot be cast to org.red5.net.websocket.WebSocketPlugin

WebSocketScopeManager manager = ((WebSocketPlugin) PluginRegistry.getPlugin("WebSocketPlugin")).getManager();

i m using red5-1.0.8-M6 version, even i compile with red5-1.0.7-release library and run on 1.0.7, same result, and also websocket-1.0.jar or websocket-1.6.jar.

How can i solve this problem?

i had deployed the chat example war to red5-1.0.8-M6 and run perfect.

Thanks

[Solved]
I have download red5-1.0.8-M8 and casting problem is sloved.
Thanks

**Comment by zksteel** [comment]
Problem still exist. I'am using red5-server 1.0.10-Release.
