### ISSUE TITLE
hello,ask a question

### ISSUE THREAD

**Issue by ydajiang** [Red5/red5-websocket#7]
my video monitoring device uploads video to the server in real time through socket.how can I push video to the other viewer, or how can the viewer pull the video stream.can red5-websocket do that ?i hope you can help me .very thanks.

**Comment by ydajiang** [comment]
sorry, my english is poor

**Comment by rajdeeprath** [comment]
No problem with language, we speak streaming :).

Welcome to Red5.!!

Few points, to make the communication clear :

1. Are you using Red5 open source or Red5 pro ? Asking cause I am not sure
what you mean by uploading via websocket.

2. Red5 open source supports RTMP only for stream delivery. Websocket is
for messaging only. If you somehow manage to upload binary data via
websocket and save it properly on server , our still can play it via only
two protocols on the open source : RTMP or http (MP4). You can also use
ffmpeg to convert it into hls segments if you want to make it playable as
hls.

3. If you want true websocket based streaming - aka webrtc, i will
recommend you join the Red5 pro channel to get answers around that.

To do so: Go to red5pro.com, create account and then join the public slack
channel.

Regards
Rajdeep Rath

**Comment by rajdeeprath** [comment]
Additionally to elaborate:

. If you want true websocket based streaming - aka webrtc, (implies using
websocket for ice exchange and UDP for streaming)
